name: Build and Deploy to Main

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          cd client
          npm ci
          npm run build

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Commit and Push Build Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Add and commit build files
          git add -f client/build
          git commit -m "Add build output" || echo "No changes to commit"

          # Push changes to the main branch
          git push origin main
